/* idt.h — the 64-bit interrupt descriptor table and the CPU's fault entry path.
 *
 * PURPOSE
 *   Until this module existed, this machine had no interrupt descriptor table at
 *   all. Every CPU exception — a stray write, a bad opcode, a divide by zero —
 *   went straight to a triple fault: QEMU reset the VM instantly, the console
 *   vanished, and the operator was left with a reboot loop and no diagnosis.
 *   On a machine whose only interface is a sentence typed at a prompt, that is
 *   the worst possible failure mode: the one record of what went wrong is the
 *   thing that gets destroyed.
 *
 *   This module installs a real IDT so that a fault becomes a *report* instead of
 *   a reset. It is the floor everything in Phase 3 stands on; fault.h is the
 *   storey above it (what was captured, how it is decoded, how it is printed).
 *
 * ARCHITECTURE
 *   Three pieces, in the order the CPU touches them:
 *
 *     1. arch/x86_64/isr.asm — 256 stubs, one per vector, generated by a NASM
 *        %rep so no vector can be forgotten. Each stub normalises the hardware's
 *        error-code asymmetry (ten vectors push one, the rest do not) by pushing
 *        a zero placeholder where the CPU pushed nothing, then pushes its own
 *        vector number and falls into one common path that saves every GPR and
 *        CR2. The C handler therefore sees one layout, always: fault_frame_t.
 *
 *     2. arch/x86_64/idt.c — this file's implementation. Builds a GDT (the one
 *        boot.asm installed has no room for a TSS), a TSS with interrupt stacks,
 *        the 256 gate descriptors, and loads all three. Also quiets the 8259s.
 *
 *     3. isr_dispatch() — the asm-to-C boundary, called with a pointer to the
 *        frame the stub just built. See fault.h for what happens next.
 *
 * WHY A TSS AND AN IST
 *   A 64-bit TSS carries no task state any more; it exists for two things, and
 *   one of them is the Interrupt Stack Table. An IST entry makes the CPU switch
 *   to a known-good stack *before* it pushes the exception frame, unconditionally
 *   and regardless of what RSP currently holds.
 *
 *   That matters here for exactly one reason: #DF (vector 8) is the exception
 *   raised when the CPU could not deliver another exception. The overwhelmingly
 *   likely cause is a corrupt or non-canonical RSP — and if RSP is unusable, then
 *   delivering #DF on that same stack fails too, which is a triple fault and a
 *   silent reset. That is precisely the outcome this whole module exists to
 *   prevent, so #DF gets IST slot 1 and its own 16 KiB stack. NMI and #MC get
 *   slots 2 and 3 on the same reasoning: both can arrive at an arbitrary
 *   instruction boundary, including one where RSP is mid-update.
 *
 *   Every other vector deliberately does NOT use an IST. This kernel is single
 *   threaded, has no userspace, and runs entirely in ring 0, so an ordinary #PF
 *   or #GP arrives with a stack that is by definition working (the faulting code
 *   was running on it). Handling those on the interrupted stack keeps RBP
 *   chaining intact, which is what makes the backtrace in fault.c useful. An IST
 *   would have thrown that away for no benefit, and IST stacks do not nest: a
 *   second fault on an IST stack silently overwrites the first frame.
 *
 * WHY THE PIC IS REMAPPED AND MASKED
 *   Nothing in this kernel uses hardware interrupts — the keyboard, the NIC and
 *   the clock are all polled, and IF has been 0 since the multiboot loader handed
 *   over. Installing an IDT does not change that, but it does change the
 *   consequences of the 8259s' power-on state, which is why idt_init() touches
 *   them:
 *
 *     - As the BIOS leaves them, IRQ0..7 are mapped to vectors 0x08..0x0F, which
 *       collide head-on with the CPU's own exception vectors. IRQ0 (the timer) is
 *       vector 8 — #DF. The moment anything set IF, an ordinary timer tick would
 *       be delivered through the double-fault gate and reported to the operator
 *       as a double fault. Remapping the master to 0x20 and the slave to 0x28
 *       removes an entire class of confident misdiagnosis.
 *     - Every line is then masked (OCW1 = 0xFF on both chips), so no device
 *       interrupt can be delivered even if some future code sets IF before the
 *       drivers are ready for it. Masking is the belt; IF = 0 is the braces.
 *
 *   Masking costs nothing today: the PIT keeps counting (time.c gates channel 2
 *   by hand and never used IRQ0), the PS/2 controller keeps buffering scancodes,
 *   and the e1000 keeps its receive ring. Only the interrupt *lines* go quiet.
 *
 * WHAT isr_dispatch() DOES WITH THE FRAME
 *   The pointer it receives is the LIVE stack image, not a copy, so anything
 *   written into it is what IRETQ restores. Phase 3b uses that: after capturing
 *   the fault it calls fault_recover(), which may patch RIP or a general
 *   register according to a plan the model armed earlier, and returning then
 *   resumes the interrupted code with the new state. Everything that decides
 *   *whether* that is allowed lives in fault.h — this file only supplies the
 *   window (from window_fill(), published once at idt_init()) that bounds any
 *   address a resume can produce.
 *
 *   Two independent guards live at this boundary, and they answer different
 *   questions. in_handler catches a fault raised while isr_dispatch() is still
 *   running — never survivable, because the reporting machinery is the thing
 *   that just broke. The same-RIP counter in fault.c catches a fault raised
 *   after a successful resume — survivable, up to a limit. Before recovery
 *   existed the first guard covered both cases by accident, because a fault
 *   could never come back.
 *
 * PUBLIC API
 *   idt_init()        — build and load the GDT, TSS and IDT; quiet the PICs,
 *                       and publish the fault window. Idempotent, and safe to
 *                       call before any driver exists.
 *   idt_installed()   — 1 once idt_init() has completed.
 *   idt_limit/base    — what LIDT was actually given, read back for reporting.
 *   idt_gate_offset() — the handler address a vector's gate points at, so a test
 *                       can prove the table was populated rather than assume it.
 *   isr_dispatch()    — the entry point isr.asm calls. Not for kernel callers.
 *
 * DEPENDENCIES
 *   io.h (outb, for the PICs), kernel.h (kputs, for the last-resort message),
 *   fault.h (everything about interpreting the frame). Deliberately not the heap
 *   and not any driver: idt_init() runs immediately after console_init(), before
 *   anything else can fault.
 *
 * FUTURE EXTENSION POINTS
 *   set_gate() is the single place a device IRQ would be hooked once anything
 *   wants one; the PIC would then be unmasked line by line rather than
 *   wholesale, and the vectors above 32 (currently reported as unexpected and
 *   ignored) would gain real handlers. That is also the point at which the
 *   interrupt gates would need reviewing: everything is an interrupt gate today
 *   because nothing here should be re-entered, but a timer IRQ that must not
 *   block the console would want the opposite.
 */
#ifndef IDT_H
#define IDT_H

#include <stdint.h>
#include <stddef.h>

#include "fault.h"

/* The architectural size of the table. All 256 are populated: an unpopulated
 * gate is a triple fault waiting for the one vector nobody thought of. */
#define IDT_ENTRIES 256

/* Segment selectors in the GDT idt_init() installs. Index 1 is byte-identical
 * to the code descriptor boot.asm loaded, so CS never has to be reloaded. */
#define SEL_KERNEL_CODE 0x08
#define SEL_KERNEL_DATA 0x10
#define SEL_TSS         0x18   /* occupies two GDT slots (system descriptors
                                * are 16 bytes in long mode) */

/* IST slots, numbered as the hardware numbers them: 1..7, with 0 meaning
 * "no stack switch". See the header comment for why only these three. */
#define IST_NONE          0
#define IST_DOUBLE_FAULT  1
#define IST_NMI           2
#define IST_MACHINE_CHECK 3
#define IST_USED          3
#define IST_STACK_SIZE    16384u

/* Gate type bits (the low nibble of the type/attr byte). An interrupt gate
 * clears IF on entry, a trap gate does not. Everything here is an interrupt
 * gate: this kernel has no reason to take a second exception while reporting
 * the first, and IF is 0 anyway. */
#define IDT_GATE_INTERRUPT 0xE
#define IDT_GATE_TRAP      0xF

/* Build the GDT/TSS/IDT and load them, then remap and mask both 8259s.
 * Call once, as early as the console allows. Safe to call twice. */
void idt_init(void);

/* 1 once idt_init() has run to completion. Read by the fault tools so the model
 * can tell "no fault has happened" from "faults cannot be caught at all". */
int idt_installed(void);

/* What LIDT was handed, read back from the descriptor this module built. Used
 * by the reporting tools rather than trusting a compile-time constant. */
uint64_t idt_base(void);
uint16_t idt_limit(void);

/* The 64-bit handler offset stored in `vector`'s gate, or 0 for an out-of-range
 * vector. Lets a test assert that all 256 gates point at real stubs. */
uint64_t idt_gate_offset(int vector);

/* The IST index configured for `vector` (0..7), or -1 if out of range. */
int idt_gate_ist(int vector);

/* The asm-to-C boundary. isr.asm calls this with RDI pointing at the frame it
 * just built on the interrupted stack. Declared here because idt.h owns the
 * calling convention; nothing in the kernel should call it directly. */
void isr_dispatch(fault_frame_t *frame);

#endif /* IDT_H */
