/* examples_json.h — the worked example documents, as C string literals.
 *
 * GENERATED by apps/examples/gen_header.py from the .json files beside it. Do not
 * edit: edit the .json and re-run
 *
 *     python3 apps/examples/gen_header.py
 *
 * tests/host/test_app_format.c reads both the .json and the string below and
 * fails if they differ, so drift is caught where it can be explained rather than
 * as a mysteriously stale window.
 *
 * WHY THE KERNEL CARRIES THEM AT ALL. They are what proves the format on real
 * hardware (apps/app_format_selftest.c launches every one at boot), and they are
 * what a model is shown when it asks what a document looks like — app.h's
 * app_example_doc(). A few kilobytes of .rodata for the ability to answer "I want
 * a clock" with a working clock is the cheapest trade in this tree.
 */
#ifndef APP_EXAMPLES_JSON_H
#define APP_EXAMPLES_JSON_H

/* apps/examples/hello.json — 468 bytes */
#define APP_HELLO_JSON \
    "{\n" \
    "  \"note\": \"The request this format existed for and could not be found doing: 'I want a window that says hello only'. No vars, no handlers - a document with only widgets is a legal app, and this is the smallest one worth shipping.\",\n" \
    "  \"title\": \"Hello\",\n" \
    "  \"width\": 220, \"height\": 90,\n" \
    "  \"grid\": { \"rows\": 1, \"cols\": 1, \"gap\": 0, \"pad\": 10 },\n" \
    "  \"widgets\": [\n" \
    "    { \"kind\": \"label\", \"name\": \"greeting\", \"text\": \"hello\",\n" \
    "      \"align\": \"center\", \"row\": 0, \"col\": 0 }\n" \
    "  ]\n" \
    "}\n"

/* apps/examples/clock.json — 681 bytes */
#define APP_CLOCK_JSON \
    "{\n" \
    "  \"note\": \"A wall clock. Two labels and one tick handler: 'clock' and 'today' are pre-rendered strings, so the whole app is two assignments. Twice a second, so the seconds never look stuck between updates.\",\n" \
    "  \"title\": \"Clock\",\n" \
    "  \"width\": 240, \"height\": 116,\n" \
    "  \"grid\": { \"rows\": 2, \"cols\": 1, \"gap\": 6, \"pad\": 10 },\n" \
    "  \"widgets\": [\n" \
    "    { \"kind\": \"label\", \"name\": \"time\", \"text\": \"--:--:--\",\n" \
    "      \"align\": \"center\", \"row\": 0, \"col\": 0 },\n" \
    "    { \"kind\": \"label\", \"name\": \"date\", \"text\": \"----------\",\n" \
    "      \"align\": \"center\", \"row\": 1, \"col\": 0 }\n" \
    "  ],\n" \
    "  \"on\": [\n" \
    "    { \"tick\": 500, \"do\": [\n" \
    "      { \"set\": \"time\", \"to\": \"clock\" },\n" \
    "      { \"set\": \"date\", \"to\": \"today\" }\n" \
    "    ] }\n" \
    "  ]\n" \
    "}\n"

/* apps/examples/stopwatch.json — 1423 bytes */
#define APP_STOPWATCH_JSON \
    "{\n" \
    "  \"note\": \"A stopwatch. 'now' is monotonic seconds since boot, so elapsed time is now-start and nothing has to be counted: a tick that is late, or one that is missed while the model is talking, still shows the right time. 'held' remembers the reading while stopped, so start resumes instead of restarting.\",\n" \
    "  \"title\": \"Stopwatch\",\n" \
    "  \"width\": 250, \"height\": 136,\n" \
    "  \"grid\": { \"rows\": 2, \"cols\": 3, \"gap\": 6, \"pad\": 10 },\n" \
    "  \"vars\": { \"start\": 0, \"held\": 0, \"run\": 0 },\n" \
    "  \"widgets\": [\n" \
    "    { \"kind\": \"field\", \"name\": \"elapsed\", \"text\": \"0.0\", \"align\": \"center\",\n" \
    "      \"readonly\": true, \"row\": 0, \"col\": 0, \"colspan\": 3 },\n" \
    "    { \"kind\": \"button\", \"text\": \"start\", \"name\": \"go\",   \"row\": 1, \"col\": 0 },\n" \
    "    { \"kind\": \"button\", \"text\": \"stop\",  \"name\": \"halt\", \"row\": 1, \"col\": 1 },\n" \
    "    { \"kind\": \"button\", \"text\": \"reset\", \"name\": \"zero\", \"row\": 1, \"col\": 2 }\n" \
    "  ],\n" \
    "  \"on\": [\n" \
    "    { \"click\": \"go\", \"do\": [\n" \
    "      { \"set\": \"start\", \"to\": \"now - held\" },\n" \
    "      { \"set\": \"run\", \"to\": \"1\" }\n" \
    "    ] },\n" \
    "    { \"click\": \"halt\", \"do\": [\n" \
    "      { \"set\": \"run\", \"to\": \"0\" }\n" \
    "    ] },\n" \
    "    { \"click\": \"zero\", \"do\": [\n" \
    "      { \"set\": \"run\", \"to\": \"0\" },\n" \
    "      { \"set\": \"held\", \"to\": \"0\" },\n" \
    "      { \"set\": \"elapsed\", \"to\": \"'0.0'\" }\n" \
    "    ] },\n" \
    "    { \"tick\": 100, \"do\": [\n" \
    "      { \"if\": \"run\", \"then\": [\n" \
    "        { \"set\": \"held\", \"to\": \"now - start\" },\n" \
    "        { \"set\": \"elapsed\", \"to\": \"cat(text(round(held * 10) / 10), ' s')\" }\n" \
    "      ] }\n" \
    "    ] }\n" \
    "  ]\n" \
    "}\n"

/* apps/examples/dice.json — 667 bytes */
#define APP_DICE_JSON \
    "{\n" \
    "  \"note\": \"Two dice. rand(6) is 0..5, so a die is rand(6)+1. Each rand() in one handler is its own draw, which is why two dice need no second statement.\",\n" \
    "  \"title\": \"Dice\",\n" \
    "  \"width\": 200, \"height\": 120,\n" \
    "  \"grid\": { \"rows\": 2, \"cols\": 1, \"gap\": 8, \"pad\": 10 },\n" \
    "  \"vars\": { \"total\": 0 },\n" \
    "  \"widgets\": [\n" \
    "    { \"kind\": \"label\", \"name\": \"faces\", \"text\": \"roll me\",\n" \
    "      \"align\": \"center\", \"row\": 0, \"col\": 0 },\n" \
    "    { \"kind\": \"button\", \"text\": \"roll\", \"name\": \"go\", \"row\": 1, \"col\": 0 }\n" \
    "  ],\n" \
    "  \"on\": [\n" \
    "    { \"click\": \"go\", \"do\": [\n" \
    "      { \"set\": \"total\", \"to\": \"rand(6) + rand(6) + 2\" },\n" \
    "      { \"set\": \"faces\", \"to\": \"cat('you rolled ', text(total))\" }\n" \
    "    ] }\n" \
    "  ]\n" \
    "}\n"

/* apps/examples/password.json — 1379 bytes */
#define APP_PASSWORD_JSON \
    "{\n" \
    "  \"note\": \"A password generator. There is no loop, so ten characters are ten statements - which is the honest shape of a bounded document: the cost of a click is visible in the document itself. at(pool, rand(32)) picks one byte of the alphabet; the alphabet omits l, o, 0 and 1 because a person has to read it back.\",\n" \
    "  \"title\": \"Password\",\n" \
    "  \"width\": 300, \"height\": 116,\n" \
    "  \"grid\": { \"rows\": 2, \"cols\": 1, \"gap\": 8, \"pad\": 10 },\n" \
    "  \"vars\": { \"pool\": \"abcdefghijkmnpqrstuvwxyz23456789\" },\n" \
    "  \"widgets\": [\n" \
    "    { \"kind\": \"field\", \"name\": \"out\", \"text\": \"press generate\",\n" \
    "      \"align\": \"center\", \"readonly\": true, \"row\": 0, \"col\": 0 },\n" \
    "    { \"kind\": \"button\", \"text\": \"generate\", \"name\": \"go\", \"row\": 1, \"col\": 0 }\n" \
    "  ],\n" \
    "  \"on\": [\n" \
    "    { \"click\": \"go\", \"do\": [\n" \
    "      { \"set\": \"out\", \"to\": \"at(pool, rand(32))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" },\n" \
    "      { \"set\": \"out\", \"to\": \"cat(out, at(pool, rand(32)))\" }\n" \
    "    ] }\n" \
    "  ]\n" \
    "}\n"

/* apps/examples/beeper.json — 1964 bytes */
#define APP_BEEPER_JSON \
    "{\n" \
    "  \"note\": \"The worked example for a capability call (include/app.h DECISION 4). A handler cannot reach a driver: it names a capability, and the kernel validates the arguments and performs it from the idle loop. hz is num(key), so one handler serves every note button - the key IS the frequency. 'into' names the field that shows what really happened: 'ok' once the sound has played, or the kernel's reason (on a machine with no audio driver, 'no audio driver'). The kernel starts at most one app sound every 500 ms, so leaning on a button gives 'too soon' rather than a queue of stale beeps.\",\n" \
    "  \"title\": \"Beeper\",\n" \
    "  \"width\": 264, \"height\": 152,\n" \
    "  \"grid\": { \"rows\": 3, \"cols\": 3, \"gap\": 6, \"pad\": 8 },\n" \
    "  \"vars\": { \"beeps\": 0 },\n" \
    "  \"widgets\": [\n" \
    "    { \"kind\": \"field\", \"name\": \"status\", \"text\": \"pick a note\",\n" \
    "      \"readonly\": true, \"row\": 0, \"col\": 0, \"colspan\": 3 },\n" \
    "    { \"kind\": \"button\", \"text\": \"440\", \"tag\": \"note\", \"row\": 1, \"col\": 0 },\n" \
    "    { \"kind\": \"button\", \"text\": \"554\", \"tag\": \"note\", \"row\": 1, \"col\": 1 },\n" \
    "    { \"kind\": \"button\", \"text\": \"659\", \"tag\": \"note\", \"row\": 1, \"col\": 2 },\n" \
    "    { \"kind\": \"button\", \"text\": \"buzz\", \"name\": \"buzz\", \"row\": 2, \"col\": 0 },\n" \
    "    { \"kind\": \"label\", \"name\": \"count\", \"text\": \"0 played\",\n" \
    "      \"align\": \"center\", \"row\": 2, \"col\": 1, \"colspan\": 2 }\n" \
    "  ],\n" \
    "  \"on\": [\n" \
    "    { \"click\": \"note\", \"do\": [\n" \
    "      { \"set\": \"status\", \"to\": \"cat('asking for ', key)\" },\n" \
    "      { \"call\": \"audio.tone\", \"with\": { \"hz\": \"num(key)\", \"ms\": \"150\" },\n" \
    "        \"into\": \"status\" },\n" \
    "      { \"set\": \"beeps\", \"to\": \"beeps + 1\" },\n" \
    "      { \"set\": \"count\", \"to\": \"cat(text(beeps), ' asked')\" }\n" \
    "    ] },\n" \
    "    { \"click\": \"buzz\", \"do\": [\n" \
    "      { \"set\": \"status\", \"to\": \"'asking for a buzz'\" },\n" \
    "      { \"call\": \"audio.tone\",\n" \
    "        \"with\": { \"hz\": \"110\", \"ms\": \"200\", \"amp\": \"12000\", \"wave\": \"'square'\" },\n" \
    "        \"into\": \"status\" },\n" \
    "      { \"set\": \"beeps\", \"to\": \"beeps + 1\" },\n" \
    "      { \"set\": \"count\", \"to\": \"cat(text(beeps), ' asked')\" }\n" \
    "    ] }\n" \
    "  ]\n" \
    "}\n"

#endif /* APP_EXAMPLES_JSON_H */
