#!/usr/bin/env python3
"""Embed the example app documents in the kernel as C string literals.

The kernel cannot read host files, so an example has to exist twice: once as
apps/examples/<name>.json (the artifact a human — or a model being shown what
good looks like — reads) and once as a C string literal inside the kernel. This
script derives the second from the first so the two cannot drift, and the host
tests read the .json files at run time and fail if they ever differ.

    python3 apps/examples/gen_header.py        # run from , or from anywhere

TWO OUTPUTS, FOR ONE HISTORICAL REASON. calculator_json.h predates the others and
is spliced between markers inside a hand-written header, because that header
carries a long comment about the reference app and tests/host/test_app.c diffs it.
Everything else lands in examples_json.h, which is generated whole. Adding an
example is one line in EXAMPLES below plus its .json file; nothing in the Makefile
changes, because apps/*.c is wildcarded and the header is checked in.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# The spliced one: (source, header, begin-marker, end-marker).
SPLICED = ("calculator.json", "calculator_json.h",
           "/* --- BEGIN GENERATED (do not edit by hand) --- */ \\\n",
           "/* --- END GENERATED --- */")

# The generated-whole one: macro name -> source file. The order is the order a
# person is likeliest to ask for the app.
EXAMPLES = [
    ("APP_HELLO_JSON",     "hello.json"),
    ("APP_CLOCK_JSON",     "clock.json"),
    ("APP_STOPWATCH_JSON", "stopwatch.json"),
    ("APP_DICE_JSON",      "dice.json"),
    ("APP_PASSWORD_JSON",  "password.json"),
    ("APP_BEEPER_JSON",    "beeper.json"),
]
EXAMPLES_HDR = "examples_json.h"

HEADER_COMMENT = """/* examples_json.h — the worked example documents, as C string literals.
 *
 * GENERATED by apps/examples/gen_header.py from the .json files beside it. Do not
 * edit: edit the .json and re-run
 *
 *     python3 apps/examples/gen_header.py
 *
 * tests/host/test_app_format.c reads both the .json and the string below and
 * fails if they differ, so drift is caught where it can be explained rather than
 * as a mysteriously stale window.
 *
 * WHY THE KERNEL CARRIES THEM AT ALL. They are what proves the format on real
 * hardware (apps/app_format_selftest.c launches every one at boot), and they are
 * what a model is shown when it asks what a document looks like — app.h's
 * app_example_doc(). A few kilobytes of .rodata for the ability to answer "I want
 * a clock" with a working clock is the cheapest trade in this tree.
 */
#ifndef APP_EXAMPLES_JSON_H
#define APP_EXAMPLES_JSON_H
"""


def literal(text):
    """The document as a continued C string literal, one line per line."""
    lines = text.split("\n")
    if lines and lines[-1] == "":
        lines.pop()                      # trailing newline, not a real line
    return "".join(
        '    "%s\\n"%s\n' % (l.replace("\\", "\\\\").replace('"', '\\"'),
                             " \\" if i + 1 < len(lines) else "")
        for i, l in enumerate(lines))


def read_doc(name):
    path = os.path.join(HERE, name)
    with open(path, "r", encoding="utf-8") as fh:
        text = fh.read()
    # A malformed example would be a rejected app and a very confusing test
    # failure, so the generator refuses to embed one.
    try:
        json.loads(text)
    except ValueError as exc:
        print("gen_header: %s is not valid JSON: %s" % (path, exc),
              file=sys.stderr)
        raise SystemExit(1)
    return text


def splice():
    src, hdr, begin, end = SPLICED
    text = read_doc(src)
    path = os.path.join(HERE, hdr)
    with open(path, "r", encoding="utf-8") as fh:
        old = fh.read()
    i, j = old.find(begin), old.find(end)
    if i < 0 or j < 0 or j < i:
        print("gen_header: markers not found in %s" % path, file=sys.stderr)
        return 1
    new = old[:i + len(begin)] + literal(text) + old[j:]
    if new == old:
        print("gen_header: %s already up to date (%d bytes)" % (hdr, len(text)))
        return 0
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(new)
    print("gen_header: rewrote %s (%d bytes of document)" % (hdr, len(text)))
    return 0


def generate():
    out = [HEADER_COMMENT]
    for macro, src in EXAMPLES:
        text = read_doc(src)
        out.append("\n/* apps/examples/%s — %d bytes */\n#define %s \\\n%s"
                   % (src, len(text), macro, literal(text)))
    out.append("\n#endif /* APP_EXAMPLES_JSON_H */\n")
    body = "".join(out)
    path = os.path.join(HERE, EXAMPLES_HDR)
    old = None
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as fh:
            old = fh.read()
    if old == body:
        print("gen_header: %s already up to date (%d examples)"
              % (EXAMPLES_HDR, len(EXAMPLES)))
        return 0
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(body)
    print("gen_header: wrote %s (%d examples, %d bytes)"
          % (EXAMPLES_HDR, len(EXAMPLES), len(body)))
    return 0


def main():
    rc = splice()
    if rc:
        return rc
    return generate()


if __name__ == "__main__":
    sys.exit(main())
